spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://127.0.0.1:8888
  # rabbitmq settings
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # h2 settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    # Bean이 생성되기 전에 ddl 실행
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notification-service;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

cloud:
  aws:
    credentials:
      ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      delivery-status-notification-queue:
        name: LotdizDeliveryStartNotificationQueue.fifo
        url: ${AWS_SQS_ENDPOINT}/LotdizDeliveryStartNotificationQueue.fifo
      project-due-date-notification-queue:
        name: LotdizProjectDueDateNotificationQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectDueDateNotificationQueue
      project-funding-rate-fail-notification-queue:
        name: LotdizProjectFundingRateFailNotificationQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectFundingRateFailNotificationQueue
      project-funding-amount-complete-notification-queue:
        name: LotdizProjectFundingAmountCompleteNotificationQueue
        url: ${AWS_SQS_ENDPOINT}/LotdizProjectFundingAmountCompleteNotificationQueue
